In [66]:
import os
import re
from pathlib import Path

import geopandas as gpd
import numpy as np
import pandas as pd

In [67]:
data_path = Path(os.environ["DATA_PATH"])
framework_path = Path(os.environ["FRAMEWORK_PATH"])
population_grids_path = Path(os.environ["GRID_PATH"])

In [68]:
df_agebs = gpd.read_file(
    population_grids_path / "final" / "zone_agebs" / "shaped" / "2020" / "02.2.03.gpkg",
).to_crs("EPSG:6372")
wanted_cvegeos = set(df_agebs["CVEGEO"].to_numpy().tolist())

In [69]:
lims = (
    gpd.read_file(data_path / "lim_aumxl24/lim_aumxl24.shp")
    .to_crs("EPSG:6372")["geometry"]
    .item()
)

# Stats

In [70]:
def fillna(col: pd.Series) -> pd.Series:
    return col.replace(["*", "N/D"], np.nan).astype(float)

In [71]:
wanted_cols = [
    "TVIVPAR",
    "TVIVPARHAB",
    "VPH_NDACMM",
    "VPH_PISOTI",
    "VPH_REFRI",
    "VPH_LAVAD",
    "VPH_HMICRO",
    "VPH_PC",
    "VPH_TV",
    "VPH_INTER",
    "POBTOT",
    "POB0_14",
    "VPH_BICI",
    "P_0A2",
    "P_3A5",
]

df_census = pd.read_csv(
    population_grids_path
    / "initial"
    / "census"
    / "INEGI"
    / "2020"
    / "conjunto_de_datos_ageb_urbana_02_cpv2020.csv",
    usecols=["ENTIDAD", "MUN", "LOC", "AGEB", "MZA"] + wanted_cols,
)

for col in wanted_cols:
    df_census = df_census.assign(**{col: lambda df: fillna(df[col])})

df_census = (
    df_census.query("MZA != 0")
    .assign(
        CVEGEO=lambda df: (
            df["ENTIDAD"].astype(str).str.zfill(2)
            + df["MUN"].astype(str).str.zfill(3)
            + df["LOC"].astype(str).str.zfill(4)
            + df["AGEB"].astype(str).str.zfill(4)
            + df["MZA"].astype(str).str.zfill(3)
        ),
        P_0A5=lambda df: df["P_0A2"] + df["P_3A5"],
    )
    .set_index("CVEGEO")
    .drop(columns=["ENTIDAD", "MUN", "LOC", "AGEB", "MZA"])
)

df_framework = (
    gpd.read_file(framework_path / "2020" / "02_bajacalifornia" / "02m.shp")
    .filter(["geometry", "CVEGEO"])
    .set_index("CVEGEO")
)

joined = (
    df_framework.join(df_census, how="inner")
    .assign(CVEGEO_AGEB=lambda df: df.index.str.slice(0, 13))
    .query("CVEGEO_AGEB in @wanted_cvegeos")
    .drop(columns=["CVEGEO_AGEB"])
)

joined = joined[joined.intersects(lims)].to_crs("EPSG:6372")
joined.to_file("./joined.gpkg")

In [72]:
rows = {
    "total_viviendas_particulares": joined["TVIVPAR"].sum(),
    "frac_viviendas_habitadas": joined["TVIVPARHAB"].sum() / joined["TVIVPAR"].sum(),
    "frac_viviendas_con_vehiculo_privado": 1
    - joined["VPH_NDACMM"].sum() / joined["TVIVPARHAB"].sum(),
    "frac_viviendas_con_piso_tierra": joined["VPH_PISOTI"].sum()
    / joined["TVIVPARHAB"].sum(),
    "frac_viviendas_con_refrigerador": joined["VPH_REFRI"].sum()
    / joined["TVIVPARHAB"].sum(),
    "frac_viviendas_con_lavadora": joined["VPH_LAVAD"].sum()
    / joined["TVIVPARHAB"].sum(),
    "frac_viviendas_con_microondas": joined["VPH_HMICRO"].sum()
    / joined["TVIVPARHAB"].sum(),
    "frac_viviendas_con_computadora": joined["VPH_PC"].sum()
    / joined["TVIVPARHAB"].sum(),
    "frac_viviendas_con_television": joined["VPH_TV"].sum()
    / joined["TVIVPARHAB"].sum(),
    "frac_viviendas_con_internet": joined["VPH_INTER"].sum()
    / joined["TVIVPARHAB"].sum(),
    "frac_viviendas_con_bicicleta": joined["VPH_BICI"].sum()
    / joined["TVIVPARHAB"].sum(),
}

stats = pd.DataFrame.from_dict(rows, orient="index", columns=["value"]).reset_index(
    names="stat",
)
stats

                                   stat          value
0          total_viviendas_particulares  290570.000000
1              frac_viviendas_habitadas       0.930960
2   frac_viviendas_con_vehiculo_privado       0.809064
3        frac_viviendas_con_piso_tierra       0.004299
4       frac_viviendas_con_refrigerador       0.973265
5           frac_viviendas_con_lavadora       0.883368
6         frac_viviendas_con_microondas       0.707074
7        frac_viviendas_con_computadora       0.542322
8         frac_viviendas_con_television       0.955525
9           frac_viviendas_con_internet       0.745125
10         frac_viviendas_con_bicicleta       0.173883

# Más lejos de alguna feature

In [ ]:
def get_pop_not_intersects(
    df: gpd.GeoDataFrame,
    features: gpd.GeoDataFrame,
    *,
    pop_col: str,
) -> float:
    idx_within = df.sjoin(features).index
    blocks_without = joined.loc[~joined.index.isin(idx_within)]
    return blocks_without[pop_col].sum() / df[pop_col].sum()

## Rutas camión

In [74]:
df_routes = (
    gpd.read_file(data_path / "RUTA_TRANSP_URB")
    .filter(["geometry"])
    .to_crs("EPSG:6372")
)

rows["frac_personas_mas_lejos_250m_autobus"] = get_pop_not_intersects(
    joined,
    df_routes.assign(geometry=lambda df: df["geometry"].buffer(250, resolution=64)),
    pop_col="POBTOT",
)

## Espacios públicos

In [75]:
public_spaces = (
    gpd.read_file(data_path / "esp_pub/esp_pub.shp")
    .to_crs("EPSG:6372")
    .assign(
        radius=lambda df: np.sqrt(df.Sup_M2 / np.pi),
        geometry=lambda df: df.apply(
            lambda x: x.geometry.buffer(x.radius, resolution=64),
            axis=1,
        ),
    )
    .query("~TIPO.isin(['CAMELLONES', 'CUCHILLAS', 'GLORIETAS'])")
    .query(
        "TIPO.isin(['JARDIN VECINAL', 'JARDINES', 'JARDINES (VIVERO MPAL)', 'PARQUE URBANO'])",
    )
)

rows["frac_ninos_0_a_14_mas_lejos_1km_parques"] = get_pop_not_intersects(
    joined,
    public_spaces.assign(
        geometry=lambda df: df["geometry"].buffer(1000, resolution=64),
    ),
    pop_col="POB0_14",
)

rows["frac_ninos_0_a_14_mas_lejos_500m_parques"] = get_pop_not_intersects(
    joined,
    public_spaces.assign(geometry=lambda df: df["geometry"].buffer(500, resolution=64)),
    pop_col="POB0_14",
)

## Escuelas

In [76]:
DENUE_TO_AMENITY_MAPPING = [
    # Salud
    {
        "name": "Consultorios médicos",
        "query": 'codigo_act.str.match("^621")',
    },
    {
        "name": "Hospital general",
        "query": 'codigo_act.str.match("^622")',
    },
    {
        "name": "Farmacia",
        "query": 'codigo_act.str.match("^46411")',
    },
    # Recreativo
    {
        "name": "Cine",
        "query": 'codigo_act.str.match("^51213")',
    },
    {
        "name": "Otros servicios recreativos",
        "query": 'codigo_act.str.match("^(71399|712|713)")',
    },
    {
        "name": "Clubs deportivos y de acondicionamiento físico",
        "query": 'codigo_act.str.match("^(71391|71394)")',
    },
    # Educación
    {
        "name": "Guarderia",
        "query": 'codigo_act.str.match("^6244")',
    },
    {
        "name": "Educación preescolar",
        "query": 'codigo_act.str.match("^61111")',
    },
    {"name": "Educación primaria", "query": 'codigo_act.str.match("^61112")'},
    {"name": "Educación secundaria", "query": 'codigo_act.str.match("^(61113|61114)")'},
    {
        "name": "Educación media superior",
        "query": 'codigo_act.str.match("^(61115|61116)")',
    },
    {"name": "Educación superior", "query": 'codigo_act.str.match("^(6112|6113)")'},
]


def process_occupancy(x: str) -> str:
    matches = re.match(r"([0-9]+) a ([0-9]+) personas", x.strip())
    return (
        (int(matches.groups()[0]) + int(matches.groups()[1])) / 2
        if matches
        else matches
    )

In [77]:
denue_base = gpd.GeoDataFrame(
    (
        pd.read_csv(
            data_path / "denue.csv",
            encoding="latin1",
        )
        .query("municipio == 'Mexicali'")
        .assign(geometry=lambda x: gpd.points_from_xy(x.longitud, x.latitud))
        .drop(columns=["municipio"])
        .set_index("clee")
        .assign(
            per_ocu=lambda x: x.per_ocu.apply(process_occupancy),
            codigo_act=lambda x: x.codigo_act.astype(str),
        )
        .dropna(subset=["per_ocu"])
        .rename(columns={"per_ocu": "num_workers"})[
            ["geometry", "codigo_act", "num_workers"]
        ]
    ),
    crs="EPSG:4326",
    geometry="geometry",
).to_crs("EPSG:6372")

for elem in DENUE_TO_AMENITY_MAPPING:
    idx = denue_base.query(elem["query"]).index
    denue_base.loc[idx, "amenity"] = elem["name"]

denue_base = denue_base.dropna(subset=["amenity"]).drop(columns=["codigo_act"])

In [78]:
schools = denue_base.query(
    "amenity.isin(['Educación preescolar', 'Educación primaria', 'Educación secundaria', 'Educación media superior', 'Educación superior'])",
)

rows["frac_personas_mas_lejos_1km_escuelas"] = get_pop_not_intersects(
    joined,
    schools.assign(geometry=lambda df: df["geometry"].buffer(1000, resolution=64)),
    pop_col="POBTOT",
)

In [79]:
rows["frac_personas_mas_lejos_1km_escuelas_preparatorias"] = get_pop_not_intersects(
    joined,
    (
        schools.query("amenity == 'Educación media superior'").assign(
            geometry=lambda df: df["geometry"].buffer(1000, resolution=64),
        )
    ),
    pop_col="POBTOT",
)

In [80]:
rows["frac_personas_mas_lejos_500m_escuelas_preparatorias"] = get_pop_not_intersects(
    joined,
    (
        schools.query("amenity == 'Educación media superior'").assign(
            geometry=lambda df: df["geometry"].buffer(500, resolution=64),
        )
    ),
    pop_col="POBTOT",
)

## Hospitales

In [81]:
rows["frac_personas_mas_lejos_1km_hospitales"] = get_pop_not_intersects(
    joined,
    (
        denue_base.query("amenity == 'Hospital general'").assign(
            geometry=lambda df: df["geometry"].buffer(1000, resolution=64),
        )
    ),
    pop_col="POBTOT",
)

## Hospitales y consultorios

In [82]:
rows["frac_personas_mas_lejos_1km_hospitales_y_consultorios"] = get_pop_not_intersects(
    joined,
    (
        denue_base.query(
            "amenity.isin(['Hospital general', 'Consultorio médico', 'Farmacia'])",
        ).assign(geometry=lambda df: df["geometry"].buffer(1000, resolution=64))
    ),
    pop_col="POBTOT",
)

In [83]:
rows["frac_personas_mas_lejos_1km_consultorios"] = get_pop_not_intersects(
    joined,
    (
        denue_base.query(
            "amenity.isin(['Consultorio médico', 'Farmacia'])",
        ).assign(geometry=lambda df: df["geometry"].buffer(1000, resolution=64))
    ),
    pop_col="POBTOT",
)

In [84]:
rows["frac_personas_mas_lejos_500m_consultorios"] = get_pop_not_intersects(
    joined,
    (
        denue_base.query(
            "amenity.isin(['Consultorio médico', 'Farmacia'])",
        ).assign(geometry=lambda df: df["geometry"].buffer(500, resolution=64))
    ),
    pop_col="POBTOT",
)

## Guarderías

In [85]:
joined

,geometry,POBTOT,P_0A2,P_3A5,POB0_14,TVIVPAR,TVIVPARHAB,VPH_PISOTI,VPH_NDACMM,VPH_REFRI,VPH_LAVAD,VPH_HMICRO,VPH_BICI,VPH_TV,VPH_PC,VPH_INTER,P_0A5
CVEGEO,,,,,,,,,,,,,,,,,
020020001661A041,"POLYGON ((1226128.826 2340913.894, 1226133.939...",80.0,3.0,5.0,23.0,26.0,23.0,0.0,NaN,22.0,22.0,15.0,NaN,22.0,16.0,17.0,8.0
0200200016094026,"POLYGON ((1228022.653 2339639.437, 1228017.636...",19.0,NaN,0.0,4.0,5.0,6.0,0.0,NaN,6.0,5.0,3.0,0.0,5.0,3.0,5.0,NaN
0200200010339046,"POLYGON ((1229515.5 2347050.012, 1229515.498 2...",51.0,0.0,0.0,5.0,18.0,17.0,0.0,3.0,17.0,15.0,13.0,7.0,17.0,10.0,13.0,0.0
0200200014666013,"POLYGON ((1231811.965 2344655.288, 1231630.887...",65.0,NaN,NaN,10.0,28.0,26.0,0.0,NaN,26.0,19.0,22.0,5.0,23.0,22.0,22.0,NaN
0200200012918027,"POLYGON ((1231171.748 2341548.929, 1231172.613...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0200200013884063,"POLYGON ((1236882.147 2347055.449, 1236911.795...",31.0,NaN,NaN,7.0,10.0,10.0,0.0,0.0,10.0,10.0,8.0,0.0,10.0,10.0,9.0,NaN
0200200013884070,"POLYGON ((1236858.112 2346974.105, 1236841.487...",19.0,0.0,0.0,NaN,5.0,5.0,0.0,0.0,5.0,5.0,4.0,NaN,5.0,5.0,5.0,0.0
0200200018495023,"POLYGON ((1240457.276 2339405.144, 1240463.604...",69.0,5.0,5.0,24.0,24.0,24.0,0.0,4.0,24.0,22.0,17.0,NaN,24.0,13.0,20.0,10.0
0200200016075024,"POLYGON ((1227226.65 2339907.616, 1227226.691 ...",251.0,9.0,13.0,55.0,78.0,76.0,0.0,12.0,75.0,68.0,55.0,13.0,71.0,47.0,64.0,22.0
0200200017020015,"POLYGON ((1233366.458 2336903.759, 1233379.333...",98.0,6.0,5.0,37.0,29.0,26.0,0.0,10.0,26.0,19.0,9.0,7.0,23.0,11.0,19.0,11.0

In [86]:
rows["frac_ninos_0_a_5_mas_lejos_500m_guarderias"] = get_pop_not_intersects(
    joined,
    (
        denue_base.query(
            "amenity.isin(['Guarderia'])",
        ).assign(geometry=lambda df: df["geometry"].buffer(500, resolution=64))
    ),
    pop_col="P_0A5",
)

rows["frac_ninos_0_a_5_mas_lejos_1km_guarderias"] = get_pop_not_intersects(
    joined,
    (
        denue_base.query(
            "amenity.isin(['Guarderia'])",
        ).assign(geometry=lambda df: df["geometry"].buffer(1000, resolution=64))
    ),
    pop_col="P_0A5",
)

# Final

In [87]:
out = pd.DataFrame.from_dict(rows, orient="index", columns=["value"]).reset_index(
    names="stat",
)
out.to_csv("./stats.csv", index=False)

In [88]:
out

                                                 stat          value
0                        total_viviendas_particulares  290570.000000
1                            frac_viviendas_habitadas       0.930960
2                 frac_viviendas_con_vehiculo_privado       0.809064
3                      frac_viviendas_con_piso_tierra       0.004299
4                     frac_viviendas_con_refrigerador       0.973265
5                         frac_viviendas_con_lavadora       0.883368
6                       frac_viviendas_con_microondas       0.707074
7                      frac_viviendas_con_computadora       0.542322
8                       frac_viviendas_con_television       0.955525
9                         frac_viviendas_con_internet       0.745125
10                       frac_viviendas_con_bicicleta       0.173883
11               frac_personas_mas_lejos_250m_autobus       0.244733
12            frac_ninos_0_a_14_mas_lejos_1km_parques       0.132454
13           frac_ninos_0_a_14_mas_lejos_500m_parques       0.407576
14               frac_personas_mas_lejos_1km_escuelas       0.007268
15  frac_personas_mas_lejos_1km_escuelas_preparato...       0.473244
16  frac_personas_mas_lejos_500m_escuelas_preparat...       0.773740
17             frac_personas_mas_lejos_1km_hospitales       0.713965
18  frac_personas_mas_lejos_1km_hospitales_y_consu...       0.048442
19           frac_personas_mas_lejos_1km_consultorios       0.049152
20          frac_personas_mas_lejos_500m_consultorios       0.208760
21         frac_ninos_0_a_5_mas_lejos_500m_guarderias       0.682050
22          frac_ninos_0_a_5_mas_lejos_1km_guarderias       0.383915